### ISSUE TITLE
[partconv~] causing segfault when edited

### ISSUE THREAD

**Issue by breedx2** [pd-externals/bsaylor#1]
It looks like editing an existing instance of `[partconv~]` and changing the table name to one that doesn't exist causes a segfault in Pd (crashes and exits).

To reproduce, take a patch like this:
![image](https://user-images.githubusercontent.com/1888255/81487020-5a46ac80-920e-11ea-84ed-fe175d66b178.png)
and edit the `[partconv~]` to change `foo` to `bar`:
![image](https://user-images.githubusercontent.com/1888255/81487038-7a766b80-920e-11ea-9a49-bfd9ec06447e.png)
(clicking on a blank bit of the canvas to accept the changes, works just fine).  Now, edit again, and change the table `bar` to `baz` (which doesn't exist), and a segfault occurs.

You can also reproduce it by creating `[partconv~ none 1024]`, which will create just fine, but any edit (even one that doesn't change contents) and it will segfault.

My environment is amd64 64-bit linux (Debian sid) with Pd 0.50.2

**Comment by umlaeute** [comment]
unable to reproduce (Debian/sid amd64; all packages installed via apt)

**Comment by umlaeute** [comment]
are you using the Debian package, or a self-compiled one?
i was able to reproduce a crash with a self-compiled package when DSP is turned on (which you haven't mentioned so I assumed it is turned off)


(PS: please provide step-by-step instructions on how to trigger the problem)

**Comment by umlaeute** [comment]
@breedx2 could you please check with b39238c to see whether this really fixes your problem?

**Comment by breedx2** [comment]
Hi @umlaeute thanks for the update!  
* My pd is from packages and `[partconv~]` is self compiled.  
* DSP Is definitely ON when this happens
* I will try b39238c5eb6033a234a1ce8bdcd16abfffaf72c1 and will let you know

**Comment by breedx2** [comment]
Confirmed!  I was no longer able to reproduce using the tip of master.  Thanks!  :beers:
