### ISSUE TITLE
version confusion

### ISSUE THREAD

**Issue by umlaeute** [pd-externals/bsaylor#2]
@lucarda uploaded a [bsaylor-0.1.4](http://deken.puredata.info/info?url=http%3A%2F%2Fpuredata.info%2FMembers%2Flucarda%2Fsoftware%2Fbsaylor%5Bv0.1.4%5D%28Windows-amd64-32%29%28Sources%29.dek) already 4 years ago, whereas this repo has tagged [bsaylor-0.1.2](https://github.com/pd-externals/bsaylor/releases/tag/v0.1.2) only 6 days ago...

**Comment by Lucarda** [comment]
There are going to be 0.1.2 working builds for win64 right?

once they are up and all is fine I delete 0.1.4 right?

EDIT: or i'm supposed to dekenize win32/64 `0.1.2` and erase `0.1.4` ?

**Comment by umlaeute** [comment]
dunno yet.

this issue is mainly a reminder to investigate the version discrepancy (e.g. which changes you did to bump the version by several numbers)

**Comment by Lucarda** [comment]
verbatim from what I (luckily) wrote in the Makefile:


```
#
#
#
# sources from https://packages.debian.org/source/stable/pd-bsaylor
#
# Source Package: pd-bsaylor (0.1-4)
#
#
# patched from pd-bsaylor_0.1-4.debian.tar.xz 
#
# MinGW needs this package:
# mingw64/mingw-w64-x86_64-fftw
#
```

back then I was just rushing to get w64 builds of many pkgs that were w32 only. i did apply the `pd-bsaylor_0.1-4.debian.tar.xz` patch.

**Comment by umlaeute** [comment]
i see.
the version should have been `0.1-4` in this case (which spells out as "4th upload of 0.1", and which sorts after `0.1` but *before* `0.1.1`).

just telling, as this is totally undocumented (so I understand why you didn't do it).

**Comment by umlaeute** [comment]
>> once they are up and all is fine I delete 0.1.4 right?
>
> dunno yet

clarification: i don't know yet, whether i will upload a w64 build of the new versions here (it basically depends on me getting my CI to properly work again with 3rd party requirements; this has rather high priority though :-)).

what I *do know*, is that I would like to prevent anybody from deleting uploads, ever.

**Comment by umlaeute** [comment]
i've just pushed v0.1.5 which should sort after 0.1.4 again.


this should also produce w64 (and w32) binaries, and upload them to deken...

**Comment by Lucarda** [comment]
&#128077;
